// SPDX-FileContributor: Daniel Vrátil <me@dvratil.cz>
//
// SPDX-License-Identifier: GPL-3.0-or-later

import QtQuick
import QtQuick.Controls as QQC2
import QtQuick.Layouts
import QtQuick.Dialogs
import org.kde.kirigami as Kirigami
import cz.dvratil.clareon

Kirigami.OverlayDrawer {
    id: drawer

    property string conversationId: ""

    signal previewRequested(int artifactId, string filename, string mimeType)

    edge: Qt.RightEdge
    width: Math.min(parent.width * 0.4, Kirigami.Units.gridUnit * 30)

    modal: true
    interactive: true
    interactiveResizeEnabled: true


    ArtifactListModel {
        id: artifactModel
        conversationId: drawer.conversationId
    }


    FileDialog {
        id: saveDialog
        fileMode: FileDialog.SaveFile
        currentFolder: "file://" + StandardPaths.writableLocation(StandardPaths.DocumentsLocation)

        property int artifactId: -1

        onAccepted: {
            if (artifactId !== -1) {
                artifactModel.saveArtifact(artifactId, selectedFile.toString().replace("file://", ""))
            }
        }
    }

    ColumnLayout {
        anchors.fill: parent
        spacing: 0

        // Header
        Kirigami.Heading {
            id: header
            Layout.fillWidth: true
            Layout.margins: Kirigami.Units.largeSpacing
            level: 2
            text: "Artifacts"
        }

        Kirigami.Separator {
            Layout.fillWidth: true
        }

        // Empty state
        Kirigami.PlaceholderMessage {
            Layout.fillWidth: true
            Layout.fillHeight: true
            visible: artifactList.count === 0

            icon.name: "folder-documents"
            text: "No artifacts yet"
            explanation: "Artifacts generated by Claude will appear here"
        }

        ListView {
            id: artifactList

            Layout.fillWidth: true
            Layout.fillHeight: true
            visible: artifactList.count > 0


            model: artifactModel
            spacing: Kirigami.Units.smallSpacing

            delegate: ArtifactDelegate {
                width: artifactList.width - Kirigami.Units.largeSpacing * 2
                x: Kirigami.Units.largeSpacing

                onDownloadRequested: (id, name) => {
                    saveDialog.artifactId = id
                    saveDialog.currentFile = name
                    saveDialog.open()
                }

                onPreviewRequested: (id, name, mime) => {
                    drawer.previewRequested(id, name, mime)
                }
            }

            section.property: "createdAt"
            section.criteria: ViewSection.FullString
            section.delegate: Kirigami.ListSectionHeader {
                width: artifactList.width
                label: formatDate(section)
            }
        }

        Kirigami.Separator {
            Layout.fillWidth: true
            visible: artifactList.count > 0
        }

        // Footer with artifact count
        QQC2.Label {
            Layout.fillWidth: true
            Layout.margins: Kirigami.Units.largeSpacing
            visible: artifactList.count > 0

            text: artifactList.count === 1 ? "1 artifact" : artifactList.count + " artifacts"
            font.pointSize: Kirigami.Theme.smallFont.pointSize
            color: Kirigami.Theme.disabledTextColor
            horizontalAlignment: Text.AlignHCenter
        }
    }

    function formatDate(timestamp) {
        const date = new Date(timestamp * 1000)
        const now = new Date()
        const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
        const yesterday = new Date(today)
        yesterday.setDate(yesterday.getDate() - 1)

        if (date >= today) {
            return "Today"
        } else if (date >= yesterday) {
            return "Yesterday"
        } else {
            return date.toLocaleDateString(Qt.locale(), "MMMM d, yyyy")
        }
    }

    function saveArtifact(artifactId, filepath) {
        artifactModel.saveArtifact(artifactId, filepath)
    }
}
